use_frameworks!

platform :ios, '9.0'

target 'ZPDeveloper_Example' do
  pod 'ZPDeveloper', :path => '../'

  target 'ZPDeveloper_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
